version: "3.8"

services:
  authservice:
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    container_name: "authservice"
    depends_on:
      - taxirabbitmq
    environment:
      - ASPNETCORE_URLS=http://+:80
      - RABBITMQ_HOST=taxirabbitmq
    ports:
      - "5001:80"

  taxiservice:
    build:
      context: .
      dockerfile: TaxiService/Dockerfile
    container_name: "taxiservice"
    depends_on:
      - taxirabbitmq
    environment:
      - ASPNETCORE_URLS=http://+:80
      - RABBITMQ_HOST=taxirabbitmq
    ports:
      - "5000:80"
  emailservice:
    build:
      context: .
      dockerfile: EmailService/Dockerfile
    container_name: "emailservice"
    depends_on:
      - taxirabbitmq
      - authservice
    environment:
      - ASPNETCORE_URLS=http://+:80
      - RABBITMQ_HOST=taxirabbitmq

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "taxiservicedb"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306" # Map container port 3306 to host port 3306

  taxirabbitmq:
    image: "rabbitmq:3-management"
    container_name: "taxirabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

