# AuthService Dockerfile.dev
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["AuthService/AuthService.csproj", "AuthService/"]
COPY ["DataLib/DataLib.csproj", "DataLib/"]
RUN dotnet restore "AuthService/AuthService.csproj"
COPY . .
WORKDIR "/src/AuthService"

# Install dotnet-ef tool
RUN dotnet tool install --global dotnet-ef

# Ensure the dotnet tools are in the PATH
ENV PATH="${PATH}:/root/.dotnet/tools"

ENTRYPOINT ["dotnet", "watch", "run", "--urls", "http://*:80"]
